export { BenefitCompanyDissolutionResource } from '@/resources/Dissolutions/benefitCompany'
export { CommunityContributionCompanyDissolutionResource } from '@/resources/Dissolutions/communityContributionCompany'
export { CooperativeDissolutionResource } from '@/resources/Dissolutions/cooperative'
export { LimitedCompanyDissolutionResource } from '@/resources/Dissolutions/limitedCompany'
export { UnlimitedDissolutionResource } from '@/resources/Dissolutions/unlimitedCompany'
