export enum AmalgamatingStatuses {
  OK,
  ERROR_AFFILIATION,
  ERROR_CCC_MISMATCH,
  ERROR_FOREIGN,
  ERROR_FOREIGN_UNLIMITED,
  ERROR_FUTURE_EFFECTIVE_FILING,
  ERROR_LIMITED_RESTORATION,
  ERROR_NIGS,
}

export enum AmlRoles {
  AMALGAMATING = 'amalgamating',
  HOLDING = 'holding'
}
