/**
 * List of actions authorized via roles. See Authorizations module.
 * Ultimately, this will be combined into the Authorization Roles enum.
 */
export enum AuthorizedActions {
  AML_OVERRIDES,
  BLANK_CERTIFY_STATE,
  BLANK_COMPLETING_PARTY,
  CONTINUATION_IN_FILING,
  COURT_ORDER_POA,
  EDITABLE_CERTIFY_NAME,
  EDITABLE_COMPLETING_PARTY,
  FILE_AND_PAY,
  FIRM_ADD_BUSINESS,
  FIRM_EDITABLE_COMPLETING_PARTY,
  FIRM_EDITABLE_EMAIL_ADDRESS,
  FIRM_NO_MIN_START_DATE,
  NO_COMPLETING_PARTY_MESSAGE_BOX,
  NO_CONTACT_INFO,
  RESTORATION_FILING,
  SAVE_DRAFT,
  SBC_BREADCRUMBS,
  STAFF_BREADCRUMBS,
  STAFF_COMMENTS,
  STAFF_PAYMENT,
  THIRD_PARTY_CERTIFY_STMT,
}
