// NB: Pay looks at both entity type + filing type code
export enum FilingCodes {
  INCORPORATION_BC = 'BCINC',
  INCORPORATION_BEN = 'BCINC',
  INCORPORATION_CC = 'BCINC',
  INCORPORATION_CP = 'OTINC',
  INCORPORATION_ULC = 'BCINC',
  DISSOLUTION_VOLUNTARY = 'DIS_VOL',
  DISSOLUTION_INVOLUNTARY = 'DIS_INVOL',
  DISSOLUTION_ADMINISTRATIVE = 'DIS_ADMIN',
  DISSOLUTION_VOLUNTARY_LIQUIDATION = 'DIS_LQD',
  DISSOLUTION_COURT_ORDERED_LIQUIDATION = 'DIS_COLQD',
  DISSOLUTION_RESTORED_IN_ERROR = 'DIS_RSTR',
  SPECIAL_RESOLUTION = 'SPRLN',
  AFFIDAVIT = 'AFDVT'
}
