export enum ItemTypes {
  TEXT = 'TEXT',
  LINK = 'LINK',
  TOOLTIP = 'TOOLTIP',
  PLACEHOLDER = 'PLACEHOLDER',
  PARTIAL_ITEMS = 'PARTIAL_ITEMS',
  BULLET_LIST = 'BULLET_LIST',
  BULLET_ITEM = 'BULLET_ITEM'
}
