export const ADDRESSCHANGED = 'addressChanged'
export const INCORPORATION_APPLICATION = 'incorporationApplication'
export const ISFUTUREEFFECTIVE = 'isFutureEffective'
export const ISIMMEDIATE = 'isImmediate'
export const REGISTRATION = 'registration'
