export const ADDRESSCHANGED = 'addressChanged'
export const ISFUTUREEFFECTIVE = 'isFutureEffective'
export const ISIMMEDIATE = 'isImmediate'
export const ISLIMITEDRESTORATION = 'isLimited'
export const ISFULLRESTORATION = 'isFull'
